# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget caffe proto)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target caffe
add_library(caffe SHARED IMPORTED)

# Create imported target proto
add_library(proto STATIC IMPORTED)

# Import target "caffe" for configuration "Debug"
set_property(TARGET caffe APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(caffe PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/code/person_pose_estimation/caffe_rtpose-master/caffe_rtpose-master/build_1/lib/Debug/caffe-d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "proto;proto;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_system-vc140-mt-gd-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_thread-vc140-mt-gd-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_filesystem-vc140-mt-gd-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_chrono-vc140-mt-gd-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_date_time-vc140-mt-gd-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_atomic-vc140-mt-gd-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/glogd.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/gflagsd.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/libprotobufd.lib;hdf5;hdf5_cpp;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/lmdb.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/leveldb.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/snappy.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cudart.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/curand.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas_device.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cudnn.lib;opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib;C:/Users/HX/Anaconda3/libs/python35.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_python-vc140-mt-gd-1_61.lib"
  IMPORTED_LOCATION_DEBUG "E:/code/person_pose_estimation/caffe_rtpose-master/caffe_rtpose-master/build_1/bin/Debug/caffe-d.dll"
  )

# Import target "proto" for configuration "Debug"
set_property(TARGET proto APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(proto PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "E:/code/person_pose_estimation/caffe_rtpose-master/caffe_rtpose-master/build_1/lib/Debug/proto-d.lib"
  )

# Import target "caffe" for configuration "Release"
set_property(TARGET caffe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(caffe PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/code/person_pose_estimation/caffe_rtpose-master/caffe_rtpose-master/build_1/lib/Release/caffe.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "proto;proto;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_system-vc140-mt-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_thread-vc140-mt-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_filesystem-vc140-mt-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_chrono-vc140-mt-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_date_time-vc140-mt-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_atomic-vc140-mt-1_61.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/glog.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/gflags.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/libprotobuf.lib;hdf5;hdf5_cpp;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/lmdb.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/leveldb.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/snappy.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cudart.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/curand.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cublas_device.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cudnn.lib;opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib;C:/Users/HX/Anaconda3/libs/python35.lib;C:/Users/HX/.caffe/dependencies/libraries_v140_x64_py35_1.1.0/libraries/lib/boost_python-vc140-mt-1_61.lib"
  IMPORTED_LOCATION_RELEASE "E:/code/person_pose_estimation/caffe_rtpose-master/caffe_rtpose-master/build_1/bin/Release/caffe.dll"
  )

# Import target "proto" for configuration "Release"
set_property(TARGET proto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(proto PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "E:/code/person_pose_estimation/caffe_rtpose-master/caffe_rtpose-master/build_1/lib/Release/proto.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
